#!/bin/bash
# install-sublime-packages

DESTINY="$HOME/.config/sublime-text-2/Packages/User/lluviaProject"
if [ ! -d $DESTINY ]; then
  mkdir -p $DESTINY
fi

cp -f sublime-text-2/*.sublime-snippet $DESTINY 
